
package com.phu;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-07-04")
public class MapResult implements org.apache.thrift.TBase<MapResult, MapResult._Fields>, java.io.Serializable, Cloneable, Comparable<MapResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapResult");

  private static final org.apache.thrift.protocol.TField MAP_PROFILE_FIELD_DESC = new org.apache.thrift.protocol.TField("mapProfile", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MapResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MapResultTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.Integer,ProfileResult> mapProfile; // required
  public int error; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAP_PROFILE((short)1, "mapProfile"),
    ERROR((short)2, "error");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAP_PROFILE
          return MAP_PROFILE;
        case 2: // ERROR
          return ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ERROR_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAP_PROFILE, new org.apache.thrift.meta_data.FieldMetaData("mapProfile", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32            , "int"), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ProfileResult.class))));
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapResult.class, metaDataMap);
  }

  public MapResult() {
  }

  public MapResult(
    java.util.Map<java.lang.Integer,ProfileResult> mapProfile,
    int error)
  {
    this();
    this.mapProfile = mapProfile;
    this.error = error;
    setErrorIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapResult(MapResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMapProfile()) {
      java.util.Map<java.lang.Integer,ProfileResult> __this__mapProfile = new java.util.HashMap<java.lang.Integer,ProfileResult>(other.mapProfile.size());
      for (java.util.Map.Entry<java.lang.Integer, ProfileResult> other_element : other.mapProfile.entrySet()) {

        java.lang.Integer other_element_key = other_element.getKey();
        ProfileResult other_element_value = other_element.getValue();

        java.lang.Integer __this__mapProfile_copy_key = other_element_key;

        ProfileResult __this__mapProfile_copy_value = new ProfileResult(other_element_value);

        __this__mapProfile.put(__this__mapProfile_copy_key, __this__mapProfile_copy_value);
      }
      this.mapProfile = __this__mapProfile;
    }
    this.error = other.error;
  }

  public MapResult deepCopy() {
    return new MapResult(this);
  }

  @Override
  public void clear() {
    this.mapProfile = null;
    setErrorIsSet(false);
    this.error = 0;
  }

  public int getMapProfileSize() {
    return (this.mapProfile == null) ? 0 : this.mapProfile.size();
  }

  public void putToMapProfile(int key, ProfileResult val) {
    if (this.mapProfile == null) {
      this.mapProfile = new java.util.HashMap<java.lang.Integer,ProfileResult>();
    }
    this.mapProfile.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.Integer,ProfileResult> getMapProfile() {
    return this.mapProfile;
  }

  public MapResult setMapProfile(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.Integer,ProfileResult> mapProfile) {
    this.mapProfile = mapProfile;
    return this;
  }

  public void unsetMapProfile() {
    this.mapProfile = null;
  }

  /** Returns true if field mapProfile is set (has been assigned a value) and false otherwise */
  public boolean isSetMapProfile() {
    return this.mapProfile != null;
  }

  public void setMapProfileIsSet(boolean value) {
    if (!value) {
      this.mapProfile = null;
    }
  }

  public int getError() {
    return this.error;
  }

  public MapResult setError(int error) {
    this.error = error;
    setErrorIsSet(true);
    return this;
  }

  public void unsetError() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERROR_ISSET_ID);
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERROR_ISSET_ID);
  }

  public void setErrorIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERROR_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MAP_PROFILE:
      if (value == null) {
        unsetMapProfile();
      } else {
        setMapProfile((java.util.Map<java.lang.Integer,ProfileResult>)value);
      }
      break;

    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MAP_PROFILE:
      return getMapProfile();

    case ERROR:
      return getError();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MAP_PROFILE:
      return isSetMapProfile();
    case ERROR:
      return isSetError();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof MapResult)
      return this.equals((MapResult)that);
    return false;
  }

  public boolean equals(MapResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_mapProfile = true && this.isSetMapProfile();
    boolean that_present_mapProfile = true && that.isSetMapProfile();
    if (this_present_mapProfile || that_present_mapProfile) {
      if (!(this_present_mapProfile && that_present_mapProfile))
        return false;
      if (!this.mapProfile.equals(that.mapProfile))
        return false;
    }

    boolean this_present_error = true;
    boolean that_present_error = true;
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (this.error != that.error)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMapProfile()) ? 131071 : 524287);
    if (isSetMapProfile())
      hashCode = hashCode * 8191 + mapProfile.hashCode();

    hashCode = hashCode * 8191 + error;

    return hashCode;
  }

  @Override
  public int compareTo(MapResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMapProfile(), other.isSetMapProfile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMapProfile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mapProfile, other.mapProfile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetError(), other.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, other.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MapResult(");
    boolean first = true;

    sb.append("mapProfile:");
    if (this.mapProfile == null) {
      sb.append("null");
    } else {
      sb.append(this.mapProfile);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("error:");
    sb.append(this.error);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MapResultStandardScheme getScheme() {
      return new MapResultStandardScheme();
    }
  }

  private static class MapResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<MapResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAP_PROFILE
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.mapProfile = new java.util.HashMap<java.lang.Integer,ProfileResult>(2*_map0.size);
                int _key1;
                @org.apache.thrift.annotation.Nullable ProfileResult _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readI32();
                  _val2 = new ProfileResult();
                  _val2.read(iprot);
                  struct.mapProfile.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setMapProfileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.error = iprot.readI32();
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mapProfile != null) {
        oprot.writeFieldBegin(MAP_PROFILE_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.mapProfile.size()));
          for (java.util.Map.Entry<java.lang.Integer, ProfileResult> _iter4 : struct.mapProfile.entrySet())
          {
            oprot.writeI32(_iter4.getKey());
            _iter4.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ERROR_FIELD_DESC);
      oprot.writeI32(struct.error);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MapResultTupleScheme getScheme() {
      return new MapResultTupleScheme();
    }
  }

  private static class MapResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<MapResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMapProfile()) {
        optionals.set(0);
      }
      if (struct.isSetError()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMapProfile()) {
        {
          oprot.writeI32(struct.mapProfile.size());
          for (java.util.Map.Entry<java.lang.Integer, ProfileResult> _iter5 : struct.mapProfile.entrySet())
          {
            oprot.writeI32(_iter5.getKey());
            _iter5.getValue().write(oprot);
          }
        }
      }
      if (struct.isSetError()) {
        oprot.writeI32(struct.error);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map6 = iprot.readMapBegin(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT); 
          struct.mapProfile = new java.util.HashMap<java.lang.Integer,ProfileResult>(2*_map6.size);
          int _key7;
          @org.apache.thrift.annotation.Nullable ProfileResult _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9)
          {
            _key7 = iprot.readI32();
            _val8 = new ProfileResult();
            _val8.read(iprot);
            struct.mapProfile.put(_key7, _val8);
          }
        }
        struct.setMapProfileIsSet(true);
      }
      if (incoming.get(1)) {
        struct.error = iprot.readI32();
        struct.setErrorIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

